/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as NumbiumRouteImport } from './routes/numbium'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as OQueFazemosIaRouteImport } from './routes/o-que-fazemos/ia'
import { Route as OQueFazemosUniversosRouteImport } from './routes/o-que-fazemos/universos'
import { Route as OQueFazemosWebRouteImport } from './routes/o-que-fazemos/web'
import { Route as SobreIndexRouteImport } from './routes/sobre/index'
import { Route as SobreIrisRouteImport } from './routes/sobre/iris'
import { Route as SobreVictorRouteImport } from './routes/sobre/victor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbiumRoute = NumbiumRouteImport.update({
  id: '/numbium',
  path: '/numbium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazemosIaRoute = OQueFazemosIaRouteImport.update({
  id: '/o-que-fazemos/ia',
  path: '/o-que-fazemos/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazemosUniversosRoute = OQueFazemosUniversosRouteImport.update({
  id: '/o-que-fazemos/universos',
  path: '/o-que-fazemos/universos',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueFazemosWebRoute = OQueFazemosWebRouteImport.update({
  id: '/o-que-fazemos/web',
  path: '/o-que-fazemos/web',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreIndexRoute = SobreIndexRouteImport.update({
  id: '/sobre/',
  path: '/sobre/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreIrisRoute = SobreIrisRouteImport.update({
  id: '/sobre/iris',
  path: '/sobre/iris',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreVictorRoute = SobreVictorRouteImport.update({
  id: '/sobre/victor',
  path: '/sobre/victor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/numbium': typeof NumbiumRoute
  '/projetos': typeof ProjetosRoute
  '/o-que-fazemos/ia': typeof OQueFazemosIaRoute
  '/o-que-fazemos/universos': typeof OQueFazemosUniversosRoute
  '/o-que-fazemos/web': typeof OQueFazemosWebRoute
  '/sobre/iris': typeof SobreIrisRoute
  '/sobre/victor': typeof SobreVictorRoute
  '/sobre/': typeof SobreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/numbium': typeof NumbiumRoute
  '/projetos': typeof ProjetosRoute
  '/o-que-fazemos/ia': typeof OQueFazemosIaRoute
  '/o-que-fazemos/universos': typeof OQueFazemosUniversosRoute
  '/o-que-fazemos/web': typeof OQueFazemosWebRoute
  '/sobre/iris': typeof SobreIrisRoute
  '/sobre/victor': typeof SobreVictorRoute
  '/sobre': typeof SobreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/numbium': typeof NumbiumRoute
  '/projetos': typeof ProjetosRoute
  '/o-que-fazemos/ia': typeof OQueFazemosIaRoute
  '/o-que-fazemos/universos': typeof OQueFazemosUniversosRoute
  '/o-que-fazemos/web': typeof OQueFazemosWebRoute
  '/sobre/iris': typeof SobreIrisRoute
  '/sobre/victor': typeof SobreVictorRoute
  '/sobre/': typeof SobreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/numbium'
    | '/projetos'
    | '/o-que-fazemos/ia'
    | '/o-que-fazemos/universos'
    | '/o-que-fazemos/web'
    | '/sobre/iris'
    | '/sobre/victor'
    | '/sobre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/numbium'
    | '/projetos'
    | '/o-que-fazemos/ia'
    | '/o-que-fazemos/universos'
    | '/o-que-fazemos/web'
    | '/sobre/iris'
    | '/sobre/victor'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/numbium'
    | '/projetos'
    | '/o-que-fazemos/ia'
    | '/o-que-fazemos/universos'
    | '/o-que-fazemos/web'
    | '/sobre/iris'
    | '/sobre/victor'
    | '/sobre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  NumbiumRoute: typeof NumbiumRoute
  ProjetosRoute: typeof ProjetosRoute
  OQueFazemosIaRoute: typeof OQueFazemosIaRoute
  OQueFazemosUniversosRoute: typeof OQueFazemosUniversosRoute
  OQueFazemosWebRoute: typeof OQueFazemosWebRoute
  SobreIrisRoute: typeof SobreIrisRoute
  SobreVictorRoute: typeof SobreVictorRoute
  SobreIndexRoute: typeof SobreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbium': {
      id: '/numbium'
      path: '/numbium'
      fullPath: '/numbium'
      preLoaderRoute: typeof NumbiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazemos/ia': {
      id: '/o-que-fazemos/ia'
      path: '/o-que-fazemos/ia'
      fullPath: '/o-que-fazemos/ia'
      preLoaderRoute: typeof OQueFazemosIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazemos/universos': {
      id: '/o-que-fazemos/universos'
      path: '/o-que-fazemos/universos'
      fullPath: '/o-que-fazemos/universos'
      preLoaderRoute: typeof OQueFazemosUniversosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-fazemos/web': {
      id: '/o-que-fazemos/web'
      path: '/o-que-fazemos/web'
      fullPath: '/o-que-fazemos/web'
      preLoaderRoute: typeof OQueFazemosWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/': {
      id: '/sobre/'
      path: '/sobre'
      fullPath: '/sobre/'
      preLoaderRoute: typeof SobreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/iris': {
      id: '/sobre/iris'
      path: '/sobre/iris'
      fullPath: '/sobre/iris'
      preLoaderRoute: typeof SobreIrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/victor': {
      id: '/sobre/victor'
      path: '/sobre/victor'
      fullPath: '/sobre/victor'
      preLoaderRoute: typeof SobreVictorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  NumbiumRoute: NumbiumRoute,
  ProjetosRoute: ProjetosRoute,
  OQueFazemosIaRoute: OQueFazemosIaRoute,
  OQueFazemosUniversosRoute: OQueFazemosUniversosRoute,
  OQueFazemosWebRoute: OQueFazemosWebRoute,
  SobreIrisRoute: SobreIrisRoute,
  SobreVictorRoute: SobreVictorRoute,
  SobreIndexRoute: SobreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
