name: Teste Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  teste:
    runs-on: ubuntu-latest

    steps:
      - name: Teste
        run: echo "GitHub Actions está funcionando"
